---
title: "01-intro"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
```

```{r}
library(here)
```

## Loading data

### tidyverse

```{r}
read_tsv(here("data", "gapminder.tsv"))
```


```{r}
df_t = read_tsv(here("data", "gapminder.tsv"))
```

```{r}
df_t = readr::read_tsv(here::here("data", "gapminder.tsv"))
```

```{r}
df_t
```

### base

```{r}
df_b = read.delim(here::here("data", "gapminder.tsv"), sep = "\t")
```

```{r}
df_b
```

## Checks


```{r}
class(df_t)
```


```{r}
class(df_b)
```

```{r}
names(df_t)
```


```{r}
names(df_b)
```

```{r}
dim(df_t)
```

```{r}
head(df_t)
```

```{r}
tail(df_b)
```

## Selecting things

###Selecting rows

#### tidyverse

```{r}
dplyr::slice(df_t, 1)
```

```{r}
df_t %>%
  dplyr::slice(1)
```

```{r}
df_t %>%
  dplyr::slice(1, 1:10)
```

#### base

```{r}
df_t[1:10, ]
```

```{r}
df_t[1, ]
```

```{r}
df_b[1, ]
```

### Selecting columns

#### tidyverse

```{r}
df_t %>%
  dplyr::select(country)
```

```{r}
df_t %>%
  dplyr::select(country, pop)
```

```{r}
df_t %>%
  dplyr::select(country:pop)
```

```{r}
df_t %>%
  dplyr::select(-country)
```

#### base

```{r}
df_b[, 'continent']
```

```{r}
df_b[, 'continent', drop=FALSE]
```

```{r}
df_b[, c('continent', 'pop'), drop=FALSE]
```

### Boolean subsets

#### tidyverse

```{r}
df_t %>%
  dplyr::filter(country == "United States")
```

```{r}
df_t %>%
  dplyr::filter(country == "United States", year == 2007)
```

```{r}
df_t %>%
  dplyr::filter(country == "United States", year == 2007)
```

#### base

```{r}
df_b[df_b$country == "United States", ]
```

```{r}
df_b[df_b$country == "United States" & df_b$year == 1952, ]
```

## Groupby

```{r}
df_b %>%
  dplyr::group_by(year) %>%
  dplyr::summarize(avg_life_exp = mean(lifeExp, na.rm = TRUE))
```

```{r}
df_b %>%
  dplyr::group_by(year, continent) %>%
  dplyr::summarise(avg_life = mean(lifeExp),
                   std_lilfe = sd(lifeExp))
```

```{r}
tips
```

## Exercise

```{r}
head(mtcars)
```

1. Filter rows by `cyl == 6` and `disp > 150`
2. What is the average `mpg` for each value of `cyl`, `gear` and `carb`?

## data.table

```{r}
library(data.table)
```

```{r}
df_d <- data.table::fread(here::here("data", "gapminder.tsv"), sep = "\t")
```

```{r}
df_d[, country]
```

```{r}
df_d[, list(country)]
```

```{r}
df_d[, list(country, pop)]
```

```{r}
df_d[, .(country, pop)]
```

```{r}
df_d[country == "United States" & year == 1952]
```

```{r}
df_d[, .(avg_life = mean(lifeExp)), by = .(year, continent)]
```

